{% set name = "paperspace" %}
{% set version = "0.0.9" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "674c422e1cf775c7ac8d31fe144191aae22a68ecef308d78559abbf0e4b6aa39" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - paperspace-python = paperspace.main:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - requests
    - boto3
    - botocore
    - six
  run:
    - python
    - requests
    - boto3
    - botocore
    - six

test:
  imports:
    - paperspace
  commands:
    - paperspace-python --help

about:
  home: https://github.com/paperspace/paperspace-python
  license: ISC License (ISCL)
  license_family: OTHER
  license_file: ''
  summary: Paperspace Python
  description: "Paperspace Python"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
