{% set name = "paperspace" %}
{% set version = "0.0.15" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b43d8216354a6fce571f3c091cbf04a52603c6a52ddfa70a7be586ec67c9eea1

build:
  number: 0
  entry_points:
    - paperspace-python = paperspace.main:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - boto3
    - botocore
    - pip
    - python
    - requests
    - six
  run:
    - boto3
    - botocore
    - python
    - requests
    - six

test:
  imports:
    - paperspace
  commands:
    - paperspace-python --help

about:
  home: https://github.com/paperspace/paperspace-python
  license: ISC (ISCL)
  license_family: OTHER
  license_file: 
  summary: Paperspace Python
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
