version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
executors:
  python-tox:
    docker:
      - image: themattrix/tox-base:latest
jobs:
  test:
    executor: python-tox
    steps:
      - checkout
      - run:
          name: Install package requirements
          command: make pip-install-dev
      - run:
          name: Run tests
          command: make run-tests

  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: install python dependencies
          command: |
            make pip-install-dev
      - run:
          name: verify git tag vs. version
          command: |
            python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[distutils]" >> ~/.pypirc
            echo -e "index-servers =" >> ~/.pypirc
            echo -e "    pypi" >> ~/.pypirc
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "repository: https://upload.pypi.org/legacy/" >> ~/.pypirc
            echo -e "username: paperspace" >> ~/.pypirc
            echo -e "password: $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            make build
      - run:
          name: upload to pypi
          command: |
            twine upload dist/*
