version: 2.1
workflows:
  master:
    jobs:
      - test:
          filters:
            branches:
              only: master
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

  pr:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: master

executors:
  python-tox:
    docker:
      - image: themattrix/tox-base:latest
jobs:
  test:
    executor: python-tox
    steps:
      - checkout
      - run:
          name: Install package requirements
          command: make pip-install-dev
      - run:
          name: Run tests
          command: make run-tests

  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Make version.py
          command: |
            if [ -n "$CIRCLE_TAG" ]; then
              VERSION="$CIRCLE_TAG"
            else
              # CIRCLE_PR_NUMBER is only set on fork prs
              PR_NUMBER="${CIRCLE_PULL_REQUEST#"https://github.com/Paperspace/gradient-cli/pull/"}"
              VERSION="0.0.0.a${PR_NUMBER}.dev${CIRCLE_BUILD_NUM}"
            fi
            echo "Publishing version $VERSION"
            echo "version = \"${VERSION}\"" > gradient/version.py
      - run:
          name: import GPG key
          command: |
            export GPG_TTY=$(tty)
            echo -e "$GPG_KEY" | gpg --import --no-tty --batch --yes --passphrase "${GPG_PASSWORD}"
      - run:
          name: install python dependencies
          command: |
            make pip-install-dev
      - run:
          name: verify git tag vs. version
          command: |
            python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[distutils]" >> ~/.pypirc
            echo -e "index-servers =" >> ~/.pypirc
            echo -e "    pypi" >> ~/.pypirc
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "repository: https://upload.pypi.org/legacy/" >> ~/.pypirc
            echo -e "username: paperspace" >> ~/.pypirc
            echo -e "password: $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            make build
      - run:
          name: sign packages
          command: |
            gpg --no-tty --batch --pinentry-mode loopback --armor --sign --local-user ${GPG_FINGERPRINT} --passphrase "${GPG_PASSWORD}" --detach-sign dist/gradient-*.*.*.tar.gz
      - run:
          name: upload to pypi
          command: |
            python -m twine upload dist/*
